validate subgraph in action

diff --git a/.github/workflows/deploy.subgraph.yaml b/.github/workflows/deploy.subgraph.yaml
--- a/.github/workflows/deploy.subgraph.yaml
+++ b/.github/workflows/deploy.subgraph.yaml
@@ -27,6 +27,11 @@ jobs:
             echo "Error: Environment must be one of 'prod', 'dev', 'testing'."
             exit 1
           fi
+          # Check if the subgraph is a valid selection
+          if [[ "${{ github.event.inputs.subgraph }}" != "beanstalk" && "${{ github.event.inputs.subgraph }}" != "bean" && "${{ github.event.inputs.subgraph }}" != "basin" && "${{ github.event.inputs.subgraph }}" != "beanft" ]]; then
+            echo "Error: Subgraph must be one of 'beanstalk', 'bean', 'basin', 'beanft'."
+            exit 1
+          fi
 
   deploy:
     needs: validation
